//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotComponentsEDEK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotComponentsEDEK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GUDEL_Track_Icon {
            get {
                object obj = ResourceManager.GetObject("GUDEL_Track_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IGUS_Track_Icon {
            get {
                object obj = ResourceManager.GetObject("IGUS_Track_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAApZINAAL6fwIAmZINAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgBhkg0AAAAAADhyeQAAMHUAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/H/////+PmsAf/////4+aQJqZmZmZqWbAH/////+PmkAAAAAAAAAAAAAAAAAAAAAA+X+xw/Gyt8PAWNvCAgB6Qy7krESSFG9BAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGUS_track_link_0 {
            get {
                return ResourceManager.GetString("IGUS_track_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAXzUAAAL6fwIAUzUAAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgAbNQAAAAAAADjYAwAANAMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/5///////ecDn//////95QErvPa2ud/6/5///////eUAAAAAAAAAAAAAAAAAAAAAAAQBQwwEAB8NWAgfCAQBQQwEAB0MAAAAAAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGUS_track_link_1 {
            get {
                return ResourceManager.GetString("IGUS_track_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAUr8DAAL6fwIARr8DAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgAOvwMAAAAAADhtFgAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/6nFtWoc1cMDD6GbjlqOJQObE/wqcaWfAeb94fsXfmkAAAAAAAAAAAAAAAAAAAAAAEdBAw9El7sJdFjq6KiXuQsb670IuAmpDAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_0 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAUXADAAL6fwIARXADAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgANcAMAAAAAADjgEwAAhxMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/hAoU2FBFcMCns2/OZpmLQFwf3JLva2zAbIIaUqg0okAAAAAAAAAAAAAAAAAAAAAAsKX3wmRRBcP//1pDAQAHQ0hLAkNuNvBDAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_1 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAA75sDAAL6fwIA45sDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgCrmwMAAAAAADi2FAAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/CWn3417rfcBcvn8RtDLvQNEAKFyqgGPAMK6xJVNZoUAAAAAAAAAAAAAAAAAAAAAAbwacwvj/6sLMzKBDEpmaQvn/6kL16WVEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_2 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAz0wDAAL6fwIAw0wDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgCLTAMAAAAAADgeFAAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/SpYRlPu2csCOTI5dW0eMQPP/////04DAak7SAHFXoEAAAAAAAAAAAAAAAAAAAAAAyG+hwuEBbsJlhkFER0CQQwEAhUKNxnFEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_3 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAXcEDAAL6fwIAUcEDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgAZwQMAAAAAADhIFgAAhxMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/luscWJFzb8B/cjEKmod1QLP9zySiuWDAJE9lCPm1pUAAAAAAAAAAAAAAAAAAAAAA/j6QQwEFZsILik9E6kP6Q8T0a0KwP3NEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_4 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAnH4DAAL6fwIAkH4DAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgBYfgMAAAAAADh9FQAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/pEA1RLJkV8AMVlMmDjJ2QCicb5EWU1DA8gfBXzREpUAAAAAAAAAAAAAAAAAAAAAA/3/FQ1jnAcLFK1JEAQAERFjnAUJiYWpEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_5 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAvoEAAAL6fwIAsoEAAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgB6gQAAAAAAADipBQAAFgYAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/YAAAAADAOMDstUWIEOtZQKhJBzqD7jPA////////Q0AAAAAAAAAAAAAAAAAAAAAA//8DRBt0n8FlRllEAUAFRBt0n0FnRmNEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_6 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRB1200_5_90_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_5_90_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAADZMDAAL6fwIAAZMDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDJkgMAAAAAADjqFgAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/U42q+hLDdsAKAefAPlCXQF66SQwCYIHAs2n+goOGtEAAAAAAAAAAAAAAAAAAAAAAVY7Iw1aigMO9Z+K7NyaJQ1aigEMvEFVDAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_0 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAEcwDAAL6fwIABcwDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDNywMAAAAAADgXGAAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/5OkR9XmQk8A7IEZqGAXwQDgWIOtqiR7BNd2u8oUaFkEAAAAAAAAAAAAAAAAAAAAAAQCEw4CHXcPCYhlDMb+yQ3jAn0OsgTBEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_1 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAhpcDAAL6fwIAepcDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgBClwMAAAAAADivFgAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/C+75jCJJbMDU2oEp64qLQJCzVyuXGZHAAAAAAJSGHkEAAAAAAAAAAAAAAAAAAAAAyhsMQk1ZnMP5v7FDinydQ67xXcIkbtNEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_2 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAYbIMAAL6fwIAVbIMAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgAdsgwAAAAAADiVUAAAmDoAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/ruOWJ36Hr8AKlEpwL4vYQAAAAAAAAHnAYwT82UoO9kAAAAAAAAAAAAAAAAAAAAAA7fq/wEI0FcO877RECkCcRED/nkNr7PVEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_3 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAFrADAAL6fwIACrADAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDSrwMAAAAAADjhFgAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/AAAAACaGHsGfW2gDECaFQA0AAAAwhh7BO24KNqm5t0AAAAAAAAAAAAAAAAAAAAAA/T/9QzoS3sLAYdBE9GDBRAEA6kL/3+hEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_4 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAANMUCAAL6fwIAKMUCAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDwxAIAAAAAADiLEQAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/AAAAAADwU8Ax9AAuWFF/QLw6MrIA+knA2rbRwD/ub0AAAAAAAAAAAAAAAAAAAAAAB6iqRAEAhsIsrdJE/5e+RAAAgEIBmOZEAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_5 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAIgYDAAL6fwIAFgYDAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDeBQMAAAAAADiHFAAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/0MwEYj+OXMCSBjAYZhR7QM89mxp0/F7AUM6DuYhwb0AAAAAAAAAAAAAAAAAAAAAAaam3RLiBg8KFZdREDQDIRJ61b0N72uREAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_6 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAFx8DAAL6fwIACx8DAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDTHgMAAAAAADiIFgAAiBMAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/AAAAAADMkMAAAAAAAMyQQAAAAAAAqJbAAAAAAAColkAAAAAAAAAAAAAAAAAAAAAA+KA7xB6CO8SDC4rDxJU7RBSeO0ScscM4AACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_platform {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRB4600_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB4600_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRBP_L300_L4000_Icon {
            get {
                object obj = ResourceManager.GetObject("IRBP_L300_L4000_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAEO8TAAL6fwIABO8TAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgDM7hMAAAAAADj5hgAAL3UAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/s00KBqKZjsAAAAAAAE6vQAAAAAAATq/AbS6Q4JylGUEAAAAAAAAAAAAAAAAAAAAAPwCHxAUO+sOlkMrDjPz/QgEA+kP3bopFAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRBP_L300_L4000_link_0 {
            get {
                return ResourceManager.GetString("IRBP_L300_L4000_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAEAAAD/////AQAAAAAAAAAMAgAAAFdSaGlub0NvbW1vbiwgVmVyc2lvbj02LjIzLjIwMDU1LjEzMTExLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPTU1MjI4MWU5N2M3NTU1MzAFAQAAABNSaGluby5HZW9tZXRyeS5NZXNoBAAAAAd2ZXJzaW9uCmFyY2hpdmUzZG0Jb3Blbm51cmJzBGRhdGEAAAAHCAgIAgIAAAAQJwAAPAAAAI1zXIwJAwAAAA8DAAAAfvwEAAL6fwIAcvwEAAAAAAD7/wIAFAAAAAAAAADk1NdOR+nTEb/lABCDASLwLbkbXPz/AgA6/AQAAAAAADgFJwAAECcAANIdM569+OX/0h0znr345f/SHTOevfjl/9IdM569+OX/JAAAAADAZcCv0Bc2Ti6RQODbfIYvD3bAkvaAGEsw3UAAAAAAAAAAAAAAAAAAAAAAAQAvwx3/LsMBACLCAQAvQx3/LkNeAYVFAACA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRBP_L300_L4000_link_1 {
            get {
                return ResourceManager.GetString("IRBP_L300_L4000_link_1", resourceCulture);
            }
        }
    }
}
