//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotComponentsEDEK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotComponentsEDEK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1j9CNLu/fxTjrpdNLdSXfGto3/2Laxx7Zt27Zt27Zt27aeb9XMi/Octc58VuX61VXVFU723LNn9q24FEX5ww9RxQ/TzU2VCk2btW5TsE2rVm1ap45fpVH7Ds3atM6dJW3GDGkzZM8UkSFt9gyZM6SOX7BTy46d2jfK3bpRp47t67VMHb9cp/otmzUo2ahbpTYtGrXOHRGRMWO2DI2yZ22QNSIiIlN6r7iTSPLstEUbtWnVqGP7bmlLN+rQ1EPf1/nv3QTqtW/QtFnnRpkatvK3aduodetO7et38DSs17Ge2KTruls8QjuZouSitmtfaaRfJYTETYU9quL+3setFNmjymfz449bifzvmT28eKVM0WcXnD2PFHuAK+HbNNti1fzJevDf3mytoirK0EiKcj5Optm7vj7683/V5+1aVR8S0XbvgaeNH0xeMCzf44N/AjObNdnbbU/X3ofuTM+n/K8fztl8B84leb2/VtQc21MmeV3g8Pc3BdK6mxdUlL55 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_0 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1juB1bs7Zn92T3VM/YtpMV27ZtO1mxjRXbtm3btrFj2/juUSs/zneu6+S+aj5P1ahRPbpn5907e2fntWk2m+0vP5SqHz6dj+qVW7Zq36FIh3btOrRPl6h6s87hrTq0z5c9Q5bMGTLnCsuWOUOuzFkzp0tUpGvbLl07N8vXvlnXLp0btU2XqGLXxm1bNSnTrGfVDm2atc+XLVuWLDkzN8uVo0mObNmyhWVyqotEldkZSjTr0K5Zl849M5RrFt7SQd3dLfIyZqPOTVq26tYsrGk7o0PHZu3bd+3cONzRtFGXRqrJ4/Ho6oRWSpstL9qpc9XRhh0TVB+VOtpt+o/+uq1YR7vczc+/ui3avzt7dPla+RLPL4X2PbZZg7Uk79LviFv3F+v+f70570e12YYTF+OHzd3z7fHf/0uHmNGuVyzWcf+yTR3ONp8xqmDdhLcnvm3Tdn/bQXEqL8+6sKDtf/1Yv+TrwaaVnIf+/q1dRLO5i5Qsoxdpn/1dEZttQIH/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_1 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jlCRbsLazqhLlyhrbtm3btm3btm3btm3b9hl7vif2zI/73bVuPyvyfSN2bGRWdc/0nJk+mkPTtD98iMqH38mlSoVmzdu0Ldi2deu2bVLFq9K4Q8fmbdvkzpImQ/o06bNnzJw+Tfb0mdKnilewc6tOnTs0zt2mcedOHeq3ShWvXOcGrZo3LNm4e6W2LRu3yZ05c4YM2dI3zp61YdbMmTNnTGfIJhHV2mmKNm7bunGnDt3TlG7csZlO3erydxtv/Q4NmzXv0jhjo9aetu0at2nTuUODjnqj+p3qS5Pb7XbKCe2kmpYLbd+h0iiPCxOSy9uZLs35va9TezjTpe7mxx+nFunfnT26dLVM0ecXw3sfa/ZAR4J3qbfHrPWT8ZX/erNtoXNYRE27EDvjnN1fH//5v9TT/MvDOi9776u1p294U4a3+c5ryWqt6NdwX7o16xNXrD4/n/a/Ptqasw58/fPiwKlT8wpGmD6jwLc/Lwp8et64kKb1y/s/Yu//iP+v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_2 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jtCRZsLYzi1lVmVlVbdu2bdu2bdu2bdu2bdvTmGm7vyf26R/3u2vd86yo943YsSN3ZtWZnu7p7tF0TdP+8CUqX6aDl2qVWrRs175w+7Zt27dLk6Ba006dW7ZvlzdbukwZ02XMmTlrxnQ5M2bJmCZB4a5tunTt1DRvu6Zdu3Rq2CZNggpdG7Vp2bh0055V2rdu2i5v1qyZMuXI2DRn9sbZs2bNmjmDWy4SWc1OV7xp+7ZNu3Tqma5s084tXNS93SIu42/YqXGLlt2aZm7S1te+Q9N27bp2atTZ1aRhl4bSZBiGQ04YSq5pedCOnaqM8TkxQXk5X8apOb73d2iHyzjV3fz449Ci/L2zJ1eulyv+8nJ4/1MtNFhP9G/anbHr/GR99N/eHPHoHBFZ0y7FzTxv79enf/4vLTUtPOXHtk4HxpUZV7d28TEFPsjzuzzgQKtyl7SO1RcU0P7X14n2Cw891NsdajqsYJHiBSYU1rWhhcYe61hE0wbk/x+x/3/E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_3 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtFzrtrbhgcIoY8a2bdu2bds2Vmzbtm3btm0n3/325Mf5TmsnV+vVnxcDNWrO7GStrGxN1zTtDz9UVz+8Bi9VKjRr3qZtwbatW7dtkypelcYdOjZv2yZ3ljQZ0qdJnz1j5vRpsqfPlD5VvIKdW3Xq3KFx7jaNO3fqUL9VqnjlOjdo1bxhycbdK7Vt2bhN7syZM2TIlr5x9qwNs2bOnDljOru6SIScO03Rxm1bN+7UoXua0o07NrMx7+zy9zLu+h0aNmvepXHGRq1dbds1btOmc4cGHW2N6neqrzZZlmWoOwwm1bRc9PYdKo10mYSAeqm9z9SM730Nrfw+U97Njz+GFunfO3t48UqZos8uhPY80oID9QRvU2+LWesn69H/7c1WLIqmDY3QtPOxM87e9fXRn/+rT34Rq9q4jm339u2Q3j19aOd8G36dSTR/W729ico2tr5tWpRP+18/fucZW1C3N9nv+a9soecFvxc8+LFlgbV5OxbStH55/0ft+R/1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_4 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN11tNvIlrdhS7Zlki1ZCicdZmZmZmamE2ZmZmZmZmZmZmZmZk7O91Ylf8w3a02eVd6/2rVV9jm5k07f2+lxKA6HI5IfooofuspL1YrNmrdpW6ht69Zt26SOXzWiQ8fmbdvkyZo2Y4a0GXJkypIhbY4MmTOkjl+oc6tOnTtE5GkT0blThwatUscv37lhq+aNSkV0r9y2ZUSbPFmyZMyYPUNEjmyNsmXJkiVTerd4E1venbZYRNvWEZ06dE9bJqJjMxd9T5e/b+Nv0KFRs+ZdIjI1bu1r2y6iTZvOHRp2dDVu0KmBGPJ6var4hGYyhyM3tX2HyqN8ToIhXmb1cTrUH31Vx7g+TvnV/IxUHVH+fWWPLl0tW+z5xfDexw5zoJLwXZrtsWv/4rz6v9nsvaM6HMNsh+PCf5nm7P72OPL/qovyZym8oXG1fXrVSklDGbvkTz6r7fholcrv++DZXy9z4cX5Hf/rR2Tfw4WqP1UOHE5VsbDicBUmF2zYoEVhh6Nf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_5 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rLt5IFbf2/+7x0qKZpWQBhpJkmRKKpUiTdKASMqQkMwklUJplrlZkxQhmVKGJjQYMkQhyizzfN571+93nuec8z3n+eN4tfb1Xtd17bXXWvd981nrXh+CJAhiCD+c5X5GUbhs33zg4CEbTRtra5tDC6ZvN7OzP2hzSHWpzGI5GTkleQU5GSW5JXILpms6WB1xsDNTPWTmcMRur9WC6ZscTKwOmmqbOW+1sTQ7pKqgsHjxMjkzJUVTRQUFBflFLPeQ8XzbMlpmNtZmR+ycZTaa2R9g4B9+9O9jRu61Mz1w8KiZ/D5rAZvDZocOOdiZ2DP79h7ZyyWNGDGC4no4RpogVGBt7bb6C9AQwtwl1YsgqF5Piojx+juaviGKmPBvZNX5RTpav7+MTftJjPEmZ7QsTBTd3Y+4y7/cZfdZgpg0jCA+i8mHp3T/HPpP1pjLfrnsZUPc6tNj6g1W3Fs3fLl3k/zLIf5HcwXxf/kZGqJXiR6JSDdbY7CKXMFyWsN8jekq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB1200_5_0_9_link_6 {
            get {
                return ResourceManager.GetString("IRB1200_5_0_9_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRB1200_5_90_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_5_90_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCTbtq7hSEQyIlm2bdu2bdu2bdu2bds2V9n2fUef88e5p7Uzn9ajf6OPEZFRtXarhcLWLJqm/eNLdfVlWLlUq9SiZbv2hdu3bdu+XZoE1Zp26tyyfbu82dJlypguY87MWTOmy5kxS8Y0CQp3bdOla6emeds17dqlU8M2aRJU6NqoTcvGpZv2rNK+ddN2ebNmzZQpR8amObM3zp41a9bMGXT1IWF5drriTdu3bdqlU890ZZt2bmFn7uwW8TGehp0at2jZrWnmJm3d7Ts0bdeua6dGne1NGnZpqA65XC6resNAck3LQ+/YqcoYt43gV5c8k22a9Wd/q5Zhsk2+Nb/+WbUokd+yJ1eulyv+4nJw/1MtMNiS6H3anbHr/Gb/+6SIszlSRte04WFNuxQ387y935/++7/6+tYtStwuvPnA8EMjEsR9e6BAvV0lDWuDgQcOtfm0982PJwW0//WVf+qJw9UWDTicqu2h3R0TjixMLrzQVrWwpg3I/z9q//+o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_0 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCXJl/fxzGMlzsks27Zt2+iybdu2bdu2bXfZtvl8I6pfzDNrTX3Wzv2LHZF5z7n3P1VdXdV3FFVRlD/8EF38CDm4VK3YrHmbtoXatm7dtk3q+FUbd+jYvG2bPFnTZsyQNkOOTFkypM2RIXOG1PELdW7VqXOHxnnaNO7cqUP9Vqnjl+/coFXzhqUad6/ctmXjNnmyZMmYMXuGxjmyNcyWJUuWTOnd4oNY8tlpizVu27pxpw7d05Zp3LGZi7m3y98PE6jfoWGz5l0aZ2rU2t+2XeM2bTp3aNDR1ah+p/rikM/nc4hXaCZTlNz09h0qj/I7CYa4nL3qVBzf+zqUg1ed8t38+ONQ7P/e2cNLV8sWe3YxvPeRYg5UE75Nsz1WrZ/sj/zvbPb4MRRlmKUoF+JkmrP766M//1dPEypUrHK5FfvWvbfjR3e/zZ89avwXLYbH3Z/71pr3g2NGLaD8rx+qMujg2Mm1D75JF6OQum9Dod8H5haa3y99YUXpl+9/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_1 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCTJt/fxzCwzK6ttTdu2bdu2bdu2bdu2bdt29/ONffrFfe5atz8rav/2jsioOmf6Dv7T01fTNU37yw9V1Q+/wUuVCs2at2lbsG3r1m3bpIpfpXGHjs3btsmdJU2G9GnSZ8+YOX2a7OkzpU8Vv2DnVp06d2icu03jzp061G+VKn65zg1aNW9YsnH3Sm1bNm6TO3PmDBmypW+cPWvDrJkzZ86YzqHeJJLcnaZo47atG3fq0D1N6cYdm9mZu7pEvI23foeGzZp3aZyxUWtP23aN27Tp3KFBR3uj+p3qq0Nut9tQnzCUVNNyUdt3qDTKYyOY6iXfEptm/OhraJmW2OSr+fnX0CL/+8oeXbpapujzi9bex1pooJ7wXertsWr9Yv/X4oiz2R5H07RhkTTtQpyMc3Z/e/z3/6r9c267UPrs/H2Zn3zpn2bQ3nzjNlZNOTXG+H3qkklD4ubX/tePrYd9BWpVn3Vwxa71BcsMnV1w0ZfaB7K0uVhI0/rl/R9r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_2 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1ztCvZvvbxSqVSqVRQqWRt27Zt27bNtW3btm3btm32tq33O+fef9z3jnH3Z8w8z/zNmUpWnzv6dPft7qM4FEX5wy+R4pdP5aVqxeYt2rYr1K5Nm3ZtU8ev2qRjpxbt2ubJmjZjhrQZcmTKkiFtjgyZM6SOXyiydefIjk3ytG0S2bljg9ap45ePbNi6RaNSTbpXbteqSds8WbJkzJg9Q5Mc2Rply5IlS6b0LvEhYfnstMWatGvTpHPH7mnLNOnUXGPu7vL3Y8wGHRs1b9GlSabGbTzt2jdp2zayY8NOWuMGnRuIS4ZhqOIbBpMpSm6yQ8fKozxOiiVejrk1Rf3eV1V2uTX50/z4oyoR/36yR5euli327KK997ESHOhI+DbN9li1f3I+6N/d7PViKMrQsKJciJNpzu6vj//8X7nl4ZRkfYau3WdOKtk+3chr+Wun90SP/qbLvp6Tbx1I3PFzfuV//ap8d+++KZmjHJz4eFPhD0+dhTNM6F7oT963hRWl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_3 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCTPlvfxrCxkZimzsk7btm3btq3Ttm3btm3btm3bzzei/y/mmbWmP2vX/sWOSJwza/Xt27e7R3EoivKXH6KLH36Vj6oVm7eIbFuobZs2bSNTx6/apEPHFm0j82RNmzFD2gw5MmXJkDZHhswZUscv1Ll1p84dmuSJbNK5U4cGrVPHL9+5YesWjUo16V65basmkXmyZMmYMXuGJjmyNcqWJUuWTOnd4iFhee+0xZq0bdOkU4fuacs06djcxVzr8u8x3gYdGjVv0aVJpsZtjLbtmkRGdu7QsKOrcYNODcQhXddV8YZWMkXJTW/fofIow0kwxcePA05F/dFXVd4ccMqv5udfVYn47yt7dOlq2WLPL4b2PlasgY6E79Jsj1X7F/tb/jubvVY0RRkWVpQLcTLN2f3t8d//q4vDSYfE3R+YWm9kT31VfrFOzzpNpDfr8u1b8yv/68fffL8LlVfvHPjc8FzhE233F37oelEw/d1nhRWlX77/UXv/R/1/M/F/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_4 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ11lNzWk7alBqlbUktqMzMzMzMzM7NnzMzMzMzMzBxzYmaImZnZ33Ov88d+e87Oc0r11lt1QZPd+Odk4lZURVF+8yWy+LI8PGpUadU6IrJoZPv2kRHpEtVo3qlz68iI/DkyZMmcIXPurNkzZ8idOVvmdImKdm3XpWun5vkjmnft0qlxu3SJKnVt0q5107LNe1aLbNs8In/27Fmy5MrcPHfOpjmzZ8+eNZNfHBJV7p2hZPPI9s27dOqZoXzzzq18+Hq3P8cYjTs1bdW6W/OszdoHIzs0j4jo2qlJZ1+zxl0ai6FAIOARN3RTKko+csdO1cYEvQhHPFLd8Cieb/09SrwbHvk23397lGj/vdmDi1cqlHx6Ibz/oeIOVpO8Sb8zbr0f9B9c/zOb60dYUUZEVZTz8bPO2/vl4e//K8vpN1UPJN8+IImnb/dCaUtczlzsaekDQ972jSzyKrKQ8r++Pi9fVUxVhh36vfx8MWPGvmKKMqCIOuORyAX/R+z/H/H/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_5 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1z2BxZt7cL3dXV3dWIbdu2bdu2bdu2jclMkskkmdi2nUxs+7vXfp4/zneu6+S+Vq3fwt5VtbvfN5NJJkvTNU37zQ/x8sMxuNSs2rpNx07FOnXo0Klj+sQ1W3Tt1qZTxwI5M2bNkjFLnmw5smTMkyV7lvSJi/Vo371H1xYFOrbo0b1rk/bpE1fu0bR9m2blWvSp3qldi44FcuTImjV3lhZ5cjXLlSNHjmyZ3XKTaGrvjKVadOrQonvXPhkrtOjW2kXe0zPiNr4mXZu1btOzRbbmHbydOrfo2LFH16bdXM2bdG8iTbZtG/KE4VSalh/fpWv18V4TEZJLpoKGZnwbZGjJChrqbb7/NrTokW/28OKViqWeXoiy55EWHqYnfZNhR7z6P6g/LxDRm3t+WNNGR9O08wmyLdz95dHv/8vnXba8fIKK1fY+KpPg/uKWvQrbrYx+E9813Fv89LAdozt3Kqz9rx+/9+wqrmt991+8fLG4PviQ6KLp2zwsrmmDC/0P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRB4600_40_2_55_link_6 {
            get {
                return ResourceManager.GetString("IRB4600_40_2_55_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRB4600_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB4600_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
